# Generated by Django 6.0.3 on 2026-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
