# Generated by Django 6.0.3 on 2026-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dailyschedule_schedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyschedule",
            unique_together={("schedule", "weekday", "pair_order", "group")},
        ),
    ]
