# Generated by Django 6.0.3 on 2026-04-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_message_is_delivered_alter_message_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoriz",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="autoriz",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="autoriz",
            name="hide_phone",
            field=models.BooleanField(
                default=False, verbose_name="Скрыть номер телефона"
            ),
        ),
        migrations.AddField(
            model_name="autoriz",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Номер телефона"
            ),
        ),
        migrations.CreateModel(
            name="ChatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interests", models.TextField(blank=True, verbose_name="Интересы")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chat_avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_profile",
                        to="app.autoriz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль для чата",
                "verbose_name_plural": "Профили для чата",
                "db_table": "List_of_chat_profiles",
            },
        ),
    ]
