# Generated by Django 6.0.3 on 2026-04-13 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_autoriz_birth_date_autoriz_gender_autoriz_hide_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="stories/")),
                ("caption", models.TextField(blank=True, null=True)),
                ("is_video", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="app.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "История",
                "verbose_name_plural": "Истории",
                "db_table": "List_of_stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
