# Generated by Django 6.0.3 on 2026-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_message_forwarded_from_message_reactions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="bonus_given",
            field=models.IntegerField(default=0, verbose_name="Выдано бонусов"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий преподавателя"
            ),
        ),
    ]
