# Generated by Django 6.0.3 on 2026-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_attendance_bonus_given_attendance_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyschedule",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Пара проведена"),
        ),
        migrations.AddField(
            model_name="dailyschedule",
            name="is_missed",
            field=models.BooleanField(default=False, verbose_name="Пара пропущена"),
        ),
        migrations.AddField(
            model_name="dailyschedule",
            name="topic",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Тема занятия"
            ),
        ),
    ]
