# Generated by Django 6.0.3 on 2026-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_dailyschedule_is_completed_dailyschedule_is_missed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworksubmission",
            name="bonus_received",
            field=models.BooleanField(
                default=False, verbose_name="Бонус за своевременную сдачу получен"
            ),
        ),
    ]
